# Generated by Django 6.0.6 on 2026-06-19 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event_Exhibition_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('allocated_badges', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='badge',
            name='exhibitor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Event_Exhibition_App.exhibitor'),
        ),
    ]
