# Generated by Django 6.0.6 on 2026-06-22 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event_Exhibition_App', '0002_exhibitor_badge_exhibitor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadbatch',
            old_name='batch_name',
            new_name='file_name',
        ),
        migrations.AddField(
            model_name='uploadbatch',
            name='invalid_records',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uploadbatch',
            name='total_records',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uploadbatch',
            name='valid_records',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='UploadRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_data', models.JSONField()),
                ('is_valid', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('is_imported', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='Event_Exhibition_App.uploadbatch')),
            ],
        ),
    ]
