# Generated by Django 6.0.6 on 2026-06-23 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event_Exhibition_App', '0003_rename_batch_name_uploadbatch_file_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadbatch',
            name='batch_name',
            field=models.CharField(default='old batch', max_length=255),
            preserve_default=False,
        ),
    ]
