# Generated by Django 6.0.6 on 2026-06-23 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event_Exhibition_App', '0004_uploadbatch_batch_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_column', models.CharField(max_length=255)),
                ('system_field', models.CharField(max_length=255)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Event_Exhibition_App.uploadbatch')),
            ],
        ),
    ]
