# Generated by Django 6.0.6 on 2026-06-25 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event_Exhibition_App', '0005_columnmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='status',
            field=models.CharField(choices=[('Invited', 'Invited'), ('Confirmed', 'Confirmed')], default='Invited', max_length=20),
        ),
    ]
