# Generated by Django 6.0.6 on 2026-06-25 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event_Exhibition_App', '0006_invitation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='terms_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
