# Generated by Django 6.0.6 on 2026-06-25 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event_Exhibition_App', '0007_badge_terms_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibitor',
            name='contact_person',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='exhibitor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='exhibitor',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='exhibitor',
            name='allocated_badges',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='exhibitor',
            name='company_name',
            field=models.CharField(max_length=200),
        ),
    ]
