# Generated by Django 6.0.6 on 2026-06-25 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event_Exhibition_App', '0008_exhibitor_contact_person_exhibitor_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exhibitor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='exhibitor',
            name='password',
        ),
        migrations.AddField(
            model_name='exhibitor',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='exhibitor',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='exhibitor',
            name='company_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='exhibitor',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
