# Generated by Django 6.0.6 on 2026-06-25 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event_Exhibition_App', '0009_remove_exhibitor_email_remove_exhibitor_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadbatch',
            name='exhibitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upload_batches', to='Event_Exhibition_App.exhibitor'),
        ),
    ]
