# Generated by Django 6.0.6 on 2026-06-25 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event_Exhibition_App', '0010_uploadbatch_exhibitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='exhibitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='Event_Exhibition_App.exhibitor'),
        ),
    ]
