# Generated by Django 6.0.6 on 2026-06-25 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event_Exhibition_App', '0011_invitation_exhibitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invitation',
            name='link_limit',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='invitation',
            name='registered_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
