# Generated by Django 6.0.6 on 2026-06-27 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event_Exhibition_App', '0013_visitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadbatch',
            name='status',
            field=models.CharField(default='processing', max_length=20),
        ),
    ]
